### PR TITLE
Grant cluster-admin for the provisioner user

### PR DESCRIPTION
**Pull request by rgolangh**
Signed-off-by: Roy Golan <rgolan@redhat.com>
Fixes: #31

### CODE REVIEW

**Comment by rgolangh** [comment]
ci build please

**Comment by rgolangh** [comment]
@cwilkers if the 'build-artifact' check will pass a new apb container will be pushed to dockerhub. Let me know if you can redeploy again using it.

**Comment by cwilkers** [comment]
@rgolangh I seem to keep getting the same error. Is the new image pushed without having to merge the PR first?

**Comment by rgolangh** [comment]
@cwilkers The comment with the 'ci please build' is invoking a build and published the artifacts. So yeah it should push a new container. I see that the apb container was published 4 hours ago, I downloaded it and checked the content and it has the updated playbook.

The latest hash of the image is:
```docker.io/rgolangh/ovirt-flexvolume-driver-apb   latest              2e9057bbfcc1```

**Comment by cwilkers** [comment]
@rgolangh I have a matching apb container, but still get the same error.

**Pull request merged**
